// src/constants/socials.js
// Real SVG brand logos from Simple Icons CDN (always up to date)
export const SOCIAL_NETWORKS = [
    {
        id: 'whatsapp',
        label: 'WhatsApp',
        color: '#25D366',
        icon: 'https://cdn.simpleicons.org/whatsapp/25D366',
        placeholder: '+229 XX XX XX XX',
        getUrl: v => `https://wa.me/${v.replace(/\D/g, '')}`,
        vcardField: (v) => `TEL;TYPE=CELL:${v}`,
    },
    {
        id: 'instagram',
        label: 'Instagram',
        color: '#E1306C',
        icon: 'https://cdn.simpleicons.org/instagram/E1306C',
        placeholder: '@votrepseudo',
        getUrl: v => `https://instagram.com/${v.replace('@', '')}`,
        vcardField: (v) => `X-SOCIALPROFILE;TYPE=instagram:${v}`,
    },
    {
        id: 'facebook',
        label: 'Facebook',
        color: '#1877F2',
        icon: 'https://cdn.simpleicons.org/facebook/1877F2',
        placeholder: 'https://facebook.com/...',
        getUrl: v => v.startsWith('http') ? v : `https://facebook.com/${v}`,
        vcardField: (v) => `X-SOCIALPROFILE;TYPE=facebook:${v}`,
    },
    {
        id: 'tiktok',
        label: 'TikTok',
        color: '#010101',
        icon: 'https://cdn.simpleicons.org/tiktok/010101',
        placeholder: '@votrepseudo',
        getUrl: v => `https://tiktok.com/@${v.replace('@', '')}`,
        vcardField: (v) => `X-SOCIALPROFILE;TYPE=tiktok:${v}`,
    },
    {
        id: 'linkedin',
        label: 'LinkedIn',
        color: '#0A66C2',
        icon: 'https://cdn.simpleicons.org/linkedin/0A66C2',
        placeholder: 'https://linkedin.com/in/...',
        getUrl: v => v.startsWith('http') ? v : `https://linkedin.com/in/${v}`,
        vcardField: (v) => `X-SOCIALPROFILE;TYPE=linkedin:${v}`,
    },
    {
        id: 'twitter',
        label: 'X (Twitter)',
        color: '#000000',
        icon: 'https://cdn.simpleicons.org/x/000000',
        placeholder: '@votrepseudo',
        getUrl: v => `https://x.com/${v.replace('@', '')}`,
        vcardField: (v) => `X-SOCIALPROFILE;TYPE=twitter:${v}`,
    },
    {
        id: 'youtube',
        label: 'YouTube',
        color: '#FF0000',
        icon: 'https://cdn.simpleicons.org/youtube/FF0000',
        placeholder: 'https://youtube.com/@...',
        getUrl: v => v.startsWith('http') ? v : `https://youtube.com/${v}`,
        vcardField: (v) => `X-SOCIALPROFILE;TYPE=youtube:${v}`,
    },
    {
        id: 'snapchat',
        label: 'Snapchat',
        color: '#FFFC00',
        icon: 'https://cdn.simpleicons.org/snapchat/FFFC00',
        placeholder: '@votrepseudo',
        getUrl: v => `https://snapchat.com/add/${v.replace('@', '')}`,
        vcardField: (v) => `X-SOCIALPROFILE;TYPE=snapchat:${v}`,
    },
    {
        id: 'telegram',
        label: 'Telegram',
        color: '#26A5E4',
        icon: 'https://cdn.simpleicons.org/telegram/26A5E4',
        placeholder: '@votrepseudo',
        getUrl: v => `https://t.me/${v.replace('@', '')}`,
        vcardField: (v) => `X-SOCIALPROFILE;TYPE=telegram:${v}`,
    },
    {
        id: 'pinterest',
        label: 'Pinterest',
        color: '#E60023',
        icon: 'https://cdn.simpleicons.org/pinterest/E60023',
        placeholder: 'https://pinterest.com/...',
        getUrl: v => v.startsWith('http') ? v : `https://pinterest.com/${v}`,
        vcardField: (v) => `X-SOCIALPROFILE;TYPE=pinterest:${v}`,
    },
    {
        id: 'github',
        label: 'GitHub',
        color: '#181717',
        icon: 'https://cdn.simpleicons.org/github/181717',
        placeholder: '@votrepseudo',
        getUrl: v => `https://github.com/${v.replace('@', '')}`,
        vcardField: (v) => `X-SOCIALPROFILE;TYPE=github:${v}`,
    },
    {
        id: 'website',
        label: 'Site Web',
        color: '#1A1265',
        icon: 'https://cdn.simpleicons.org/googlechrome/1A1265',
        placeholder: 'https://votresite.com',
        getUrl: v => v.startsWith('http') ? v : `https://${v}`,
        vcardField: (v) => `URL:${v}`,
    },
];

export const LINK_ICONS = [
    { emoji: '🔗', label: 'Lien' },
    { emoji: '📄', label: 'Document' },
    { emoji: '🛒', label: 'Boutique' },
    { emoji: '📧', label: 'Email' },
    { emoji: '📞', label: 'Téléphone' },
    { emoji: '📍', label: 'Localisation' },
    { emoji: '🎵', label: 'Musique' },
    { emoji: '🎥', label: 'Vidéo' },
    { emoji: '📸', label: 'Portfolio' },
    { emoji: '⭐', label: 'Avis' },
    { emoji: '💼', label: 'CV' },
    { emoji: '🎯', label: 'Promo' },
];
